site_name: 'Bash-my-AWS'
site_description: 'CLI Commands for Managing AWS Resources'
site_author: 'Mike Bailey'
site_url: 'https://bash-my-aws.org/'
google_analytics: ['UA-154550647-1', 'bash-my-aws.org']

nav:
  - Home: index.md
  # - Tour: tour.md
  - Command Reference: command-reference.md
  - Pipe-Skimming: pipe-skimming.md
  - CloudFormation Naming: cloudformation-naming.md
  - LinuxConf 2020: linuxconf2020.md

theme:
  name: material
repo_name: 'bash-my-aws/bash-my-aws'
repo_url: 'https://github.com/bash-my-aws/bash-my-aws'
extra:
  social:
    - type: 'github'
      link: 'https://github.com/bash-my-aws'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true



