site_name: 'bash-my-aws'
site_description: 'CLI Tools for Managing AWS'
site_author: 'Mike Bailey'
site_url: 'https://bash-my-aws.github.io/'
google_analytics: ['UA-154550647-1', 'bash-my-aws.org']

nav:
  - Home: index.md
  # - Tour: tour.md
  - Command Reference: command-reference.md

theme:
  name: material
repo_name: 'bash-my-aws/bash-my-aws'
repo_url: 'https://github.com/bash-my-aws/bash-my-aws'
extra:
  social:
    - type: 'github'
      link: 'https://github.com/bash-my-aws'
    - type: 'twitter'
      link: 'https://twitter.com/bashmyaws'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true



